import type { Entry } from "./types/entries.js";

export let ENTRIES: Entry[] = [
  {
    id: 1,
    db_id: 1,
    title: "Baby Driver",
    release_date: "March 11th, 2017",
    start_date: "July 7th, 2026",
    finish_date: "July 7th, 2026",
    status: "completed",
    progress: "100%",
    user_rating: 10,
    review: "",
    liked: true,
    tags: ["soundtrack", "driving"],
  },
  {
    id: 2,
    db_id: 2,
    title: "Neuromancer",
    release_date: "March 11th, 2017",
    start_date: "July 7th, 2026",
    status: "completed",
    progress: "5%",
    liked: false,
    tags: ["cyberpunk", "gritty"],
  },
  {
    id: 3,
    db_id: 23,
    title: "Minecraft",
    release_date: "March 11th, 2017",
    start_date: "July 7th, 2016",
    finish_date: "February 6th, 2026",
    status: "completed",
    progress: "100%",
    user_rating: 10,
    review: "I Love Minecraft",
    liked: true,
    tags: ["soundtrack", "sandbox", "nostalgic"],
  },
  {
    id: 4,
    db_id: 14,
    title: "Squid Game",
    release_date: "September 12th, 2011",
    start_date: "July 7th, 2026",
    finish_date: "August 25th, 2026",
    status: "completed",
    progress: "100%",
    user_rating: 9,
    review: "",
    liked: true,
    tags: ["korean", "death games"],
  },
];
